/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import scene from "../assets/3d/dalaran.glb";
import { useFrame, useThree } from "@react-three/fiber";

const Dalaran = ({ isRotating, setIsRotating, setCurrentStage, ...props }) => {
  const islandRef = useRef();

  const { gl, viewport } = useThree();
  const { nodes, materials, animations } = useGLTF(scene);

  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.95;

  const { actions } = useAnimations(animations, islandRef);

  const handlePointerDown = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);

    const clientX = e.touches ? e.touches[0].clientX : e.clientX;

    lastX.current = clientX;
  };

  const handlePointerUp = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);
  };

  const handlePointerMove = (e) => {
    e.stopPropagation();
    e.preventDefault();

    if (isRotating) {
      const clientX = e.touches ? e.touches[0].clientX : e.clientX;

      const delta = (clientX - lastX.current) / viewport.width;

      islandRef.current.rotation.y += delta * 0.01 * Math.PI;

      lastX.current = clientX;

      rotationSpeed.current = delta * 0.01 * Math.PI;
    }
  };

  const handleKeyDown = (e) => {
    if (e.key == "ArrowLeft") {
      if (!isRotating) setIsRotating(true);

      islandRef.current.rotation.y += 0.005 * Math.PI;
      rotationSpeed.current = 0.007;
    } else if (e.key == "ArrowRight") {
      if (!isRotating) setIsRotating(true);

      islandRef.current.rotation.y -= 0.005 * Math.PI;
      rotationSpeed.current = -0.007;
    }
  };

  const handleKeyUp = (e) => {
    if (e.key === "ArrowLeft" || e.key === "ArrowRight") {
      setIsRotating(false);
    }
  };

  useFrame(() => {
    if (!isRotating) {
      rotationSpeed.current *= dampingFactor;

      if (Math.abs(rotationSpeed.current) < 0.001) {
        rotationSpeed.current = 0;
      }

      islandRef.current.rotation.y += rotationSpeed.current;
    } else {
      const rotation = islandRef.current.rotation.y;

      const normalizedRotation =
        ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

      // Set the current stage based on the island's orientation
      // switch (true) {
      //   case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
      //     setCurrentStage(4);
      //     break;
      //   case normalizedRotation >= 0.85 && normalizedRotation <= 1.3:
      //     setCurrentStage(3);
      //     break;
      //   case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
      //     setCurrentStage(2);
      //     break;
      //   case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
      //     setCurrentStage(1);
      //     break;
      //   default:
      //     setCurrentStage(null);
      // }
    }
  });

  useEffect(() => {
    actions["Armature.001|MainTowerIdle"].play();

    const canvas = gl.domElement;
    canvas.addEventListener("pointerdown", handlePointerDown);
    canvas.addEventListener("pointerup", handlePointerUp);
    canvas.addEventListener("pointermove", handlePointerMove);
    document.addEventListener("keydown", handleKeyDown);
    document.addEventListener("keyup", handleKeyUp);

    return () => {
      canvas.removeEventListener("pointerdown", handlePointerDown);
      canvas.removeEventListener("pointerup", handlePointerUp);
      canvas.removeEventListener("pointermove", handlePointerMove);
      document.removeEventListener("keydown", handleKeyDown);
      document.removeEventListener("keyup", handleKeyUp);
    };
  }, [gl, handlePointerDown, handlePointerUp, handlePointerMove]);

  return (
    <group ref={islandRef} {...props} dispose={null}>
      <group name="AuxScene">
        <group name="Sketchfab_Scene">
          <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
            <group
              name="512cae3324734c8a9144b6c8a8a539d1fbx"
              rotation={[Math.PI / 2, 0, 0]}
              position={[10, -1100, 0]}
            >
              <group name="Object_2">
                <group name="RootNode">
                  <group
                    name="TowerV1004"
                    position={[-633.208, -481.55, -2312.723]}
                  >
                    <mesh
                      name="TowerV1004_TowerSet1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV1004_TowerSet1_0.geometry}
                      material={materials.TowerSet1}
                    />
                  </group>
                  <group
                    name="TowerV1006"
                    position={[1066.193, -480.389, -977.116]}
                  >
                    <mesh
                      name="TowerV1006_TowerSet1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV1006_TowerSet1_0.geometry}
                      material={materials.TowerSet1}
                    />
                  </group>
                  <group
                    name="TowerV1007"
                    position={[398.589, -481.866, -99.737]}
                  >
                    <mesh
                      name="TowerV1007_TowerSet1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV1007_TowerSet1_0.geometry}
                      material={materials.TowerSet1}
                    />
                  </group>
                  <group
                    name="TowerV1008"
                    position={[-448.298, -482.756, -17.643]}
                  >
                    <mesh
                      name="TowerV1008_TowerSet1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV1008_TowerSet1_0.geometry}
                      material={materials.TowerSet1}
                    />
                  </group>
                  <group
                    name="TowerV3016"
                    position={[403.951, -188.838, -1061.885]}
                  >
                    <mesh
                      name="TowerV3016_TowerSet1Red_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3016_TowerSet1Red_0.geometry}
                      material={materials.TowerSet1Red}
                    />
                    <mesh
                      name="TowerV3016_TowerSet1Glass_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3016_TowerSet1Glass_0.geometry}
                      material={materials.TowerSet1Glass}
                    />
                  </group>
                  <group
                    name="TowerV2001"
                    position={[-805.637, -335.305, -1321.382]}
                  >
                    <mesh
                      name="TowerV2001_TowerSet1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV2001_TowerSet1_0.geometry}
                      material={materials.TowerSet1}
                    />
                    <mesh
                      name="TowerV2001_GlassEmission_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV2001_GlassEmission_0.geometry}
                      material={materials.GlassEmission}
                    />
                  </group>
                  <group
                    name="TowerV2002"
                    position={[560.533, -335.305, -1768.982]}
                  >
                    <mesh
                      name="TowerV2002_TowerSet1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV2002_TowerSet1_0.geometry}
                      material={materials.TowerSet1}
                    />
                    <mesh
                      name="TowerV2002_GlassEmission_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV2002_GlassEmission_0.geometry}
                      material={materials.GlassEmission}
                    />
                  </group>
                  <group
                    name="TowerV3019"
                    position={[539.466, -188.839, -1060.707]}
                  >
                    <mesh
                      name="TowerV3019_TowerSet2Red_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3019_TowerSet2Red_0.geometry}
                      material={materials.TowerSet2Red}
                    />
                    <mesh
                      name="TowerV3019_TowerSet2Glasses_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3019_TowerSet2Glasses_0.geometry}
                      material={materials.TowerSet2Glasses}
                    />
                  </group>
                  <group
                    name="TowerV3017"
                    position={[638.053, -188.838, -950.974]}
                  >
                    <mesh
                      name="TowerV3017_TowerSet2Red_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3017_TowerSet2Red_0.geometry}
                      material={materials.TowerSet2Red}
                    />
                    <mesh
                      name="TowerV3017_TowerSet2Glasses_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3017_TowerSet2Glasses_0.geometry}
                      material={materials.TowerSet2Glasses}
                    />
                  </group>
                  <group
                    name="TowerV3020"
                    position={[439.387, -188.838, -849.837]}
                  >
                    <mesh
                      name="TowerV3020_TowerSet2Red_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3020_TowerSet2Red_0.geometry}
                      material={materials.TowerSet2Red}
                    />
                  </group>
                  <group
                    name="TowerV1003"
                    position={[436.492, -188.838, -944.304]}
                  >
                    <mesh
                      name="TowerV1003_TowerSet1Red_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV1003_TowerSet1Red_0.geometry}
                      material={materials.TowerSet1Red}
                    />
                  </group>
                  <group
                    name="TowerV3021"
                    position={[475.741, -188.838, -770.531]}
                  >
                    <mesh
                      name="TowerV3021_TowerSet1Red_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3021_TowerSet1Red_0.geometry}
                      material={materials.TowerSet1Red}
                    />
                    <mesh
                      name="TowerV3021_TowerSet1Glass_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3021_TowerSet1Glass_0.geometry}
                      material={materials.TowerSet1Glass}
                    />
                  </group>
                  <group
                    name="TowerV3022"
                    position={[579.545, -188.839, -836.743]}
                  >
                    <mesh
                      name="TowerV3022_TowerSet2Red_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3022_TowerSet2Red_0.geometry}
                      material={materials.TowerSet2Red}
                    />
                    <mesh
                      name="TowerV3022_TowerSet2Glasses_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3022_TowerSet2Glasses_0.geometry}
                      material={materials.TowerSet2Glasses}
                    />
                  </group>
                  <group
                    name="TowerV3023"
                    position={[91.499, -188.838, -1861.179]}
                  >
                    <mesh
                      name="TowerV3023_TowerSet2Blue_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3023_TowerSet2Blue_0.geometry}
                      material={materials.TowerSet2Blue}
                    />
                    <mesh
                      name="TowerV3023_TowerSet2Glasses_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3023_TowerSet2Glasses_0.geometry}
                      material={materials.TowerSet2Glasses}
                    />
                  </group>
                  <group
                    name="TowerV3024"
                    position={[236.243, -188.839, -1751.817]}
                  >
                    <mesh
                      name="TowerV3024_TowerSet2Blue_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3024_TowerSet2Blue_0.geometry}
                      material={materials.TowerSet2Blue}
                    />
                    <mesh
                      name="TowerV3024_TowerSet2Glasses_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3024_TowerSet2Glasses_0.geometry}
                      material={materials.TowerSet2Glasses}
                    />
                  </group>
                  <group
                    name="TowerV3025"
                    position={[-93.128, -194.645, -1907.69]}
                  >
                    <mesh
                      name="TowerV3025_TowerSet2Blue_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3025_TowerSet2Blue_0.geometry}
                      material={materials.TowerSet2Blue}
                    />
                    <mesh
                      name="TowerV3025_TowerSet2Glasses_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3025_TowerSet2Glasses_0.geometry}
                      material={materials.TowerSet2Glasses}
                    />
                  </group>
                  <group
                    name="TowerV1005"
                    position={[73.013, -188.838, -1721.608]}
                  >
                    <mesh
                      name="TowerV1005_TowerSet1Blue_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV1005_TowerSet1Blue_0.geometry}
                      material={materials.TowerSet1Blue}
                    />
                  </group>
                  <group
                    name="TowerV3028"
                    position={[-18.623, -188.838, -1737.448]}
                  >
                    <mesh
                      name="TowerV3028_TowerSet1Blue_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3028_TowerSet1Blue_0.geometry}
                      material={materials.TowerSet1Blue}
                    />
                    <mesh
                      name="TowerV3028_TowerSet1Glass_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3028_TowerSet1Glass_0.geometry}
                      material={materials.TowerSet1Glass}
                    />
                  </group>
                  <group
                    name="TowerV3027"
                    position={[53.296, -188.838, -1655.287]}
                  >
                    <mesh
                      name="TowerV3027_TowerSet2Blue_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3027_TowerSet2Blue_0.geometry}
                      material={materials.TowerSet2Blue}
                    />
                  </group>
                  <group
                    name="TowerV3026"
                    position={[146.704, -188.838, -1667.79]}
                  >
                    <mesh
                      name="TowerV3026_TowerSet1Blue_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3026_TowerSet1Blue_0.geometry}
                      material={materials.TowerSet1Blue}
                    />
                    <mesh
                      name="TowerV3026_TowerSet1Glass_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3026_TowerSet1Glass_0.geometry}
                      material={materials.TowerSet1Glass}
                    />
                  </group>
                  <group
                    name="Plane"
                    position={[-123.279, -187.367, -1480.305]}
                  >
                    <mesh
                      name="Plane_Ground_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Plane_Ground_0.geometry}
                      material={materials.Ground}
                    />
                  </group>
                  <group
                    name="Circle"
                    position={[-480.077, -188.838, -1371.618]}
                  >
                    <mesh
                      name="Circle_Ground_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Circle_Ground_0.geometry}
                      material={materials.Ground}
                    />
                  </group>
                  <group
                    name="BezierCurve"
                    position={[-639.156, -479.522, -186.369]}
                  >
                    <mesh
                      name="BezierCurve_DalaranTree_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.BezierCurve_DalaranTree_0.geometry}
                      material={materials.DalaranTree}
                    />
                    <mesh
                      name="BezierCurve_Leaf_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.BezierCurve_Leaf_0.geometry}
                      material={materials.Leaf}
                    />
                  </group>
                  <group
                    name="BezierCurve001"
                    position={[-529.891, -188.838, -1048.356]}
                  >
                    <mesh
                      name="BezierCurve001_DalaranTree_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.BezierCurve001_DalaranTree_0.geometry}
                      material={materials.DalaranTree}
                    />
                    <mesh
                      name="BezierCurve001_Leaf_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.BezierCurve001_Leaf_0.geometry}
                      material={materials.Leaf}
                    />
                  </group>
                  <group
                    name="BezierCurve002"
                    position={[-791.837, -332.277, -1623.889]}
                  >
                    <mesh
                      name="BezierCurve002_DalaranTree_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.BezierCurve002_DalaranTree_0.geometry}
                      material={materials.DalaranTree}
                    />
                    <mesh
                      name="BezierCurve002_Leaf_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.BezierCurve002_Leaf_0.geometry}
                      material={materials.Leaf}
                    />
                  </group>
                  <group
                    name="BezierCurve003"
                    position={[96.786, -188.838, -1186.384]}
                  >
                    <mesh
                      name="BezierCurve003_DalaranTree_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.BezierCurve003_DalaranTree_0.geometry}
                      material={materials.DalaranTree}
                    />
                    <mesh
                      name="BezierCurve003_Leaf_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.BezierCurve003_Leaf_0.geometry}
                      material={materials.Leaf}
                    />
                  </group>
                  <group
                    name="BezierCurve004"
                    position={[532.939, -336.976, -513.959]}
                  >
                    <mesh
                      name="BezierCurve004_DalaranTree_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.BezierCurve004_DalaranTree_0.geometry}
                      material={materials.DalaranTree}
                    />
                    <mesh
                      name="BezierCurve004_Leaf_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.BezierCurve004_Leaf_0.geometry}
                      material={materials.Leaf}
                    />
                  </group>
                  <group
                    name="BezierCurve005"
                    position={[317.043, -190.882, -558.081]}
                  >
                    <mesh
                      name="BezierCurve005_DalaranTree_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.BezierCurve005_DalaranTree_0.geometry}
                      material={materials.DalaranTree}
                    />
                    <mesh
                      name="BezierCurve005_Leaf_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.BezierCurve005_Leaf_0.geometry}
                      material={materials.Leaf}
                    />
                  </group>
                  <group
                    name="BezierCurve006"
                    position={[696.091, -332.278, -1274.174]}
                  >
                    <mesh
                      name="BezierCurve006_DalaranTree_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.BezierCurve006_DalaranTree_0.geometry}
                      material={materials.DalaranTree}
                    />
                    <mesh
                      name="BezierCurve006_Leaf_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.BezierCurve006_Leaf_0.geometry}
                      material={materials.Leaf}
                    />
                  </group>
                  <group
                    name="BezierCurve007"
                    position={[-201.919, -334.245, -180.097]}
                  >
                    <mesh
                      name="BezierCurve007_DalaranTree_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.BezierCurve007_DalaranTree_0.geometry}
                      material={materials.DalaranTree}
                    />
                    <mesh
                      name="BezierCurve007_Leaf_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.BezierCurve007_Leaf_0.geometry}
                      material={materials.Leaf}
                    />
                  </group>
                  <group name="Circle001" position={[-150.087, 0, -644.174]}>
                    <mesh
                      name="Circle001_MainBaseBottom_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Circle001_MainBaseBottom_0.geometry}
                      material={materials.MainBaseBottom}
                    />
                  </group>
                  <group
                    name="Plane004"
                    position={[-27.367, -260.558, -1188.843]}
                  >
                    <mesh
                      name="Plane004_MainIsland_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Plane004_MainIsland_0.geometry}
                      material={materials.MainIsland}
                    />
                  </group>
                  <group name="TowerV1001" position={[83.415, 0, -748.01]}>
                    <mesh
                      name="TowerV1001_TowerSet1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV1001_TowerSet1_0.geometry}
                      material={materials.TowerSet1}
                    />
                  </group>
                  <group name="TowerV1002" position={[-384.489, 0, -748.01]}>
                    <mesh
                      name="TowerV1002_TowerSet1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV1002_TowerSet1_0.geometry}
                      material={materials.TowerSet1}
                    />
                  </group>
                  <group name="TowerV3005" position={[-150, 0, -488.716]}>
                    <mesh
                      name="TowerV3005_TowerSet2Building_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3005_TowerSet2Building_0.geometry}
                      material={materials.TowerSet2Building}
                    />
                    <mesh
                      name="TowerV3005_TowerSet2Glasses_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3005_TowerSet2Glasses_0.geometry}
                      material={materials.TowerSet2Glasses}
                    />
                  </group>
                  <group name="TowerV3007" position={[-150, 0, -933.222]}>
                    <mesh
                      name="TowerV3007_TowerSet2Building_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3007_TowerSet2Building_0.geometry}
                      material={materials.TowerSet2Building}
                    />
                  </group>
                  <group name="TowerV3008" position={[-150, 0, -800]}>
                    <mesh
                      name="TowerV3008_TowerSet2Building_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3008_TowerSet2Building_0.geometry}
                      material={materials.TowerSet2Building}
                    />
                    <mesh
                      name="TowerV3008_TowerSet2Glasses_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3008_TowerSet2Glasses_0.geometry}
                      material={materials.TowerSet2Glasses}
                    />
                  </group>
                  <group name="TowerV3009" position={[-0.601, 0, -795.848]}>
                    <mesh
                      name="TowerV3009_TowerSet2Building_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3009_TowerSet2Building_0.geometry}
                      material={materials.TowerSet2Building}
                    />
                    <mesh
                      name="TowerV3009_TowerSet2Glasses_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3009_TowerSet2Glasses_0.geometry}
                      material={materials.TowerSet2Glasses}
                    />
                  </group>
                  <group name="TowerV3010" position={[5.744, 0, -644.174]}>
                    <mesh
                      name="TowerV3010_TowerSet2Building_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3010_TowerSet2Building_0.geometry}
                      material={materials.TowerSet2Building}
                    />
                    <mesh
                      name="TowerV3010_TowerSet2Glasses_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3010_TowerSet2Glasses_0.geometry}
                      material={materials.TowerSet2Glasses}
                    />
                  </group>
                  <group name="TowerV3011" position={[-305.917, 0, -644.174]}>
                    <mesh
                      name="TowerV3011_TowerSet2Building_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3011_TowerSet2Building_0.geometry}
                      material={materials.TowerSet2Building}
                    />
                    <mesh
                      name="TowerV3011_TowerSet2Glasses_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3011_TowerSet2Glasses_0.geometry}
                      material={materials.TowerSet2Glasses}
                    />
                  </group>
                  <group name="TowerV3012" position={[-299.488, 0, -795.848]}>
                    <mesh
                      name="TowerV3012_TowerSet2Building_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3012_TowerSet2Building_0.geometry}
                      material={materials.TowerSet2Building}
                    />
                    <mesh
                      name="TowerV3012_TowerSet2Glasses_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3012_TowerSet2Glasses_0.geometry}
                      material={materials.TowerSet2Glasses}
                    />
                  </group>
                  <group
                    name="TowerV3014"
                    position={[6.224, 128.783, -644.174]}
                  >
                    <mesh
                      name="TowerV3014_TowerSet3Building_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3014_TowerSet3Building_0.geometry}
                      material={materials.TowerSet3Building}
                    />
                    <mesh
                      name="TowerV3014_TowerSet3Glass_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3014_TowerSet3Glass_0.geometry}
                      material={materials.TowerSet3Glass}
                    />
                  </group>
                  <group
                    name="TowerV3015"
                    position={[-150.956, 266.628, -490.27]}
                  >
                    <mesh
                      name="TowerV3015_TowerSet3Building_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3015_TowerSet3Building_0.geometry}
                      material={materials.TowerSet3Building}
                    />
                    <mesh
                      name="TowerV3015_TowerSet3Glass_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3015_TowerSet3Glass_0.geometry}
                      material={materials.TowerSet3Glass}
                    />
                  </group>
                  <group
                    name="TowerV3018"
                    position={[-305.917, 209.722, -644.174]}
                  >
                    <mesh
                      name="TowerV3018_TowerSet3Building_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3018_TowerSet3Building_0.geometry}
                      material={materials.TowerSet3Building}
                    />
                    <mesh
                      name="TowerV3018_TowerSet3Glass_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TowerV3018_TowerSet3Glass_0.geometry}
                      material={materials.TowerSet3Glass}
                    />
                  </group>
                  <group
                    name="Armature001"
                    position={[-154.877, 910.349, -649.777]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                  >
                    <group name="Object_122">
                      <primitive object={nodes._rootJoint} />
                      <skinnedMesh
                        name="Object_157"
                        geometry={nodes.Object_157.geometry}
                        material={materials.TowerSet3Building}
                        skeleton={nodes.Object_157.skeleton}
                      />
                      <skinnedMesh
                        name="Object_158"
                        geometry={nodes.Object_158.geometry}
                        material={materials.TowerSet3Glass}
                        skeleton={nodes.Object_158.skeleton}
                      />
                      <group
                        name="TowerV3003"
                        position={[-0.068, 0.054, -3.622]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.01}
                      >
                        <mesh
                          name="TowerV3003_TowerSet3Building_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.TowerV3003_TowerSet3Building_0.geometry
                          }
                          material={materials.TowerSet3Building}
                        />
                        <mesh
                          name="TowerV3003_TowerSet3Glass_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.TowerV3003_TowerSet3Glass_0.geometry}
                          material={materials.TowerSet3Glass}
                        />
                      </group>
                      <group
                        name="Object_156"
                        position={[-155.752, 1055.56, -568.747]}
                      />
                    </group>
                  </group>
                  <group
                    name="TowerV3001"
                    position={[-155.752, 1055.56, -568.747]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

export default Dalaran;
