/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import dragonScene from "../assets/3d/dragon.glb";

const Dragon = ({ isRotating, ...props }) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(dragonScene);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (isRotating) {
      actions["BenPao"].play();
    } else {
      actions["ZhanLi"].play();
    }
  }, [actions, isRotating]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="AuxScene">
        <group name="AuxScene_1">
          <group name="Sketchfab_Scene">
            <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
              <group
                name="drgonwhitefbx"
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
              >
                <group name="Object_2">
                  <group name="RootNode">
                    <group name="Object_4">
                      <primitive object={nodes._rootJoint} />
                      <skinnedMesh
                        name="Object_7"
                        geometry={nodes.Object_7.geometry}
                        material={materials.BaiLongZuoQi}
                        skeleton={nodes.Object_7.skeleton}
                      />
                      <group name="Object_6" rotation={[-Math.PI / 2, 0, 0]} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

export default Dragon;
